/* global Zotero */
// The Alignment Science Blog uses Distill elements and CSS-generated bylines.
// Its front matter sometimes has authors: [null], so read the actual byline.
Zotero.ResearchAnthropic = {
	extract() {
		if (location.hostname !== 'alignment.anthropic.com') return null;
		const article = document.querySelector('d-article');
		const heading = document.querySelector('d-title h1');
		if (!article || !heading) return null;
		const clean = text => text.replace(/\s+/g, ' ').trim();
		const byline = article.querySelector('.section-authors')?.cloneNode(true);
		let names = [], date;
		if (byline) {
			const published = [...byline.querySelectorAll('[style]')].find(node => node.style.float === 'right');
			const dateText = clean(byline.dataset.published || published?.textContent || '');
			if (dateText) date = Zotero.Date.strToISO(dateText) || dateText;
			published?.remove();
			for (const node of byline.querySelectorAll('sup')) node.remove();
			const rows = byline.dataset.author ? [byline.dataset.author] : [...byline.childNodes].map(node => {
				if (node.nodeType === Node.TEXT_NODE) return node.textContent;
				if (node.nodeType !== Node.ELEMENT_NODE || !node.matches('p, div')) return '';
				const row = node.cloneNode(true);
				// Author rows are direct children; the affiliations sit inside a
				// nested paragraph, below those rows, and are not authors.
				for (const child of row.querySelectorAll('p, div')) child.remove();
				return row.textContent;
			});
			names = rows.flatMap(row => clean(row).split(/,\s*(?:and\s+)?|\s+and\s+/)).map(clean).filter(Boolean);
		}
		let description;
		try {
			description = JSON.parse(document.querySelector('d-front-matter script')?.textContent || '{}').description;
		} catch { /* Keep the translated abstract when front matter is unavailable. */ }
		const post = article.cloneNode(true);
		for (const node of post.querySelectorAll('script, style, noscript, nav, .section-authors')) node.remove();
		for (const node of post.querySelectorAll('br')) node.replaceWith('\n');
		for (const node of post.querySelectorAll('p, div, h1, h2, h3, h4, h5, h6, li, pre, blockquote, section, table, tr, figure, figcaption, details, summary')) {
			node.prepend('\n'); node.append('\n');
		}
		for (const node of post.querySelectorAll('th, td')) node.append('\t');
		for (const node of post.querySelectorAll('d-footnote')) { node.prepend(' ('); node.append(') '); }
		return {
			title: clean(heading.textContent), names, date, description,
			pageText: post.textContent.replace(/[ \t]+\n/g, '\n').replace(/\n{3,}/g, '\n\n').trim()
		};
	},
	applyMetadata(item, article) {
		item.itemType = 'blogPost';
		item.blogTitle = 'Alignment Science Blog';
		if (article.title) item.title = article.title;
		if (article.date) item.date = article.date;
		if (!item.abstractNote && typeof article.description === 'string') item.abstractNote = article.description;
		if (article.names.length) {
			const remaining = [...(item.creators || [])];
			const authors = article.names.map(name => {
				const index = remaining.findIndex(creator => creator.creatorType === 'author'
					&& [creator.firstName, creator.lastName].filter(Boolean).join(' ') === name);
				return index < 0 ? Zotero.Utilities.cleanAuthor(name, 'author') : remaining.splice(index, 1)[0];
			});
			item.creators = [...authors, ...remaining];
		}
	}
};
